name: Format Check

on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting with Prettier
        run: npx prettier --check 'src/**/*.ts'

      - name: Report formatting issues
        if: failure()
        run: |
          echo "Formatting issues detected. Run 'npm run format' locally to fix."
          npx prettier --list-different 'src/**/*.ts'